
export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const FETCH_ARTICLES_BY_AUTHOR = 'FETCH_ARTICLES_BY_AUTHOR';
export const FETCH_ARTICLES_BY_AUTHOR_SUCCEEDED = 'FETCH_ARTICLES_BY_AUTHOR_SUCCEEDED';
export const FETCH_SUCCEEDED = 'FETCH_SUCCEEDED';
export const FETCH_FAILED = 'FETCH_FAILED';

export const FETCH_UPDATE_ARTICLE = 'FETCH_UPDATE_ARTICLE'
export const FETCH_UPDATE_ARTICLE_SUCCEEDED = 'FETCH_UPDATE_ARTICLE_SUCCEEDED'
export const FETCH_UPDATE_ARTICLE_FAILED = 'FETCH_UPDATE_ARTICLE_FAILED'

